name: drawingtasks
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.7
  - graphviz
  - imageio
  - numpy
  - Pillow
  - pytest
  - pip
  - frozendict
  - pycairo
  - num2words
  - dill
  - pip:
    - phx-class-registry